# Generated by Django 4.2.26 on 2025-12-06 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_alter_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='songplay',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='True if play is from anonymous user'),
        ),
        migrations.AlterField(
            model_name='songplay',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song_plays', to=settings.AUTH_USER_MODEL),
        ),
    ]
