# Generated by Django 4.2.26 on 2026-06-20 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artist_user'),
        ('music', '0003_songplay_is_anonymous_alter_songplay_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AddField(
            model_name='song',
            name='display_artist_name',
            field=models.CharField(blank=True, help_text='Optional: Artist name to display (different from linked artist)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes part of duration (0-59)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='song',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Seconds part of duration (0-59)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='song',
            name='featured_artists',
            field=models.ManyToManyField(blank=True, related_name='featured_songs', to='artists.artist'),
        ),
    ]
