# Generated by Django 4.2.26 on 2025-12-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
    ]
