# Generated by Django 4.2.26 on 2025-12-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_remove_artist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
